//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DosyaTakip
{
    using System;
    using System.Collections.Generic;
    
    public partial class DosyaOlaylari
    {
        public int Id { get; set; }
        public string Yol { get; set; }
        public System.DateTime OlaySaati { get; set; }
        public int EylemTurID { get; set; }
    
        public virtual EylemTurleri EylemTurleri { get; set; }
    }
}
